# -*- coding: utf-8 -*-
"""CelciusTOfarhenite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11nG4w-6nyruF4lzHqJz-mbCaf52TMTDK
"""

import tensorflow as tf
import numpy as np
import logging

celsius_q    = np.array([-40, -10,  0,  8, 15, 22,  38, 45, 60],  dtype=float)
fahrenheit_a = np.array([-40,  14, 32, 46, 59, 72, 100, 113,  140],  dtype=float)

l0 = tf.keras.layers.Dense(units=1, input_shape=[1]) 
model = tf.keras.Sequential([l0])
model.compile(loss='mean_squared_error', optimizer=tf.keras.optimizers.Adam(0.1))
history = model.fit(celsius_q, fahrenheit_a, epochs=500, verbose=False)

print(model.predict([100.0]))